language: node_js
node_js:
  - 16
os: linux
sudo: true
services:
  - docker

before_install:
  - docker build -t frontend-app -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-040625511858"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  edge: true

