on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed
env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  NAME: ${{ secrets.DOCKER_NAME }}
  PASSWORD: ${{ secrets.DOCKER_PWD }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: [ubuntu-latest]

    steps:
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ env.LOGIN }}
          password: ${{ env.PASSWORD }}
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t "$LOGIN/$NAME:$GITHUB_REF:11" -f Dockerfile .
      - name: Push image to docker.io
        run: docker push "${{ env.LOGIN }}/${{ env.NAME }}:${GITHUB_REF:11}"
